### ISSUE TITLE
This project is amazing

### ISSUE THREAD

**Issue by pjankiewicz** [gridbugs/caw#2]
I was looking through Rust synthesisers projects to gain some inspiration and discover good patterns.
Just browsing through the code I find it really well thought implementation of how synths should be build in Rust.
I learned a lot just reading it.

I wanted to experiment with resynthesis -> wave to patch. Your code would be ideal to experiment with it.

I thought I could contribute AST to define signals as expressions that can be converted to signals.

Have you thought about a license?

**Comment by gridbugs** [comment]
Oops haha I forgot to add a license. I'll add one. Also heads up that I'm currently in the process of rewriting most of this project in the *-next crates

**Comment by gridbugs** [comment]
Added a license.

**Comment by pjankiewicz** [comment]
Thanks for the answer. I saw these next crates - those changes make sense especially the builder proc macros. I have a pretty complete implementation of converting signals to expressions.

I used some proc macros on top of your existing builder.

But now I can build graphs dynamically

```rust
use caw::prelude::*;
use crate::expr::{Expr, Terminal};

pub fn piano_expr() -> Expr {
    let gate = Expr::PeriodicGate {
        freq: Box::new(Expr::Constant(Terminal::Freq(Freq::from_hz(0.5)))),
        duty_01: Some(Box::new(Expr::Constant(Terminal::F64(0.1)))),
        offset_01: Some(Box::new(Expr::Constant(Terminal::F64(0.0)))),
    };

    let osc = Expr::Oscillator {
        waveform: Box::new(Expr::Constant(Terminal::Waveform(Waveform::Sine))),
        freq: Box::new(Expr::Constant(Terminal::Freq(Freq::from_hz(440.0)))),
        pulse_width_01: None,
        reset_trigger: None,
        reset_offset_01: None,
        hard_sync: None,
    };

    let env = Expr::AdsrLinear01 {
        key_down: Box::new(gate.clone()),
        key_press: None,
        attack_s: Some(Box::new(Expr::Constant(Terminal::F64(0.01)))),
        decay_s: Some(Box::new(Expr::Constant(Terminal::F64(0.2)))),
        sustain_01: Some(Box::new(Expr::Constant(Terminal::F64(0.8)))),
        release_s: Some(Box::new(Expr::Constant(Terminal::F64(0.3)))),
    };

    let filtered_osc = Expr::ApplyFilter {
        signal: Box::new(osc),
        filter: Box::new(Expr::LowPassButterworth {
            cutoff_hz: Box::new(Expr::Add(
                Box::new(Expr::Constant(Terminal::F64(1000.0))),
                Box::new(Expr::Mul(
                    Box::new(Expr::Constant(Terminal::F64(800.0))),
                    Box::new(env.clone()),
                )),
            )),
            filter_order_half: None,
        }),
    };

    Expr::Mul(Box::new(filtered_osc), Box::new(env))
}
```

**Comment by gridbugs** [comment]
Oh cool!

Do you plan on generating `Signal<f64>`s or something from the asts?

In the *-next crates I've made a change where signals are unboxed, so patch functions would typically return something like ﻿`SigBuf<impl Sig<Item=f32>>`. To translate from an ast to one of these at runtime you would need to explicitly box the signals again (e.g. implement the `Sig` trait for `Box<dyn Sig<Item=f32>>` or something and then box each signal in the generated patch. That would have a performance cost but might make it easier to quickly experiment.

Also if you plan to build on top of the *-next crates bear in mind that I'm constantly rearranging and renaming things at the moment!

**Comment by pjankiewicz** [comment]
You can take a look here https://github.com/pjankiewicz/caw/tree/main/core/src/ast

Basically Expr can be converted to Value (all signal types). What I struggled a bit and this is far from being finished are all ways how you can convert one type of a signal to another (needed as input to a node). From this perspective it makes sense to implement TryFrom for everything almost - because when I convert the expression to a signal it is not guaranteed that I will get a proper type as the result of some signal graph.

From the ast perspective it probably doesn't matter if the signal is buffered or not - or so I think.

My big plan was to create an ast to start evolving patches with some evolutionary algorithms. I implemented Cartesian Genetic Programming and it can create some random patches although it is not very efficient search. But even then ast can be useful to serialize/deserialize patches if you planned to do it.

**Comment by gridbugs** [comment]
Ooh evolving patches sounds really interesting. I'd love to see/hear some of the patches produced by your search!
